version: '3.4'

services:
  proyecto7front:
    image: proyecto7front
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
